-- ══════════════════════════════════════════════════════════════════════════
-- FASE 3 — STRATEGY EVOLUTION ENGINE
-- supabase-phase3-setup.sql — idempotent, additief. 1× draaien in de
-- Supabase SQL Editor (net als phase 1 en 2).
--
-- Bouwt voort op de Fase-2 research-tabellen. Nieuw:
--   strategy_registry        — immutable strategy-versies + lifecycle
--   strategy_activations     — audit trail van ELKE lifecycle-stap
--   strategy_paper_metrics   — monitoring-snapshots per actieve versie
--
-- VEILIGHEID OP DATABASENIVEAU:
--   • status-constraint zonder enige LIVE-status — fysiek onmogelijk om
--     via deze tabellen een strategie live te zetten
--   • unieke (strategy_id, version) — immutable versies, geen stille edits
--   • indexes voor de hot paths (status-lookups per minuut-tick)
-- ══════════════════════════════════════════════════════════════════════════

-- ── 1. strategy_registry ─────────────────────────────────────────────────
create table if not exists strategy_registry (
  id                   bigint generated by default as identity primary key,
  created_at           timestamptz not null default now(),

  -- identiteit (immutable)
  strategy_id          text not null,            -- slug, bijv. rsi-dip-volfilter
  family               text not null,            -- bijv. RSI-MEAN-REVERSION
  version              text not null,            -- semver, bijv. 2.0.0
  parent_strategy_id   text,                     -- lineage (parent van deze mutatie)
  parent_version       text,

  -- herkomst uit de Research Engine (Fase 2)
  origin_candidate_id  bigint,                   -- research_candidates.id
  research_run_id      text,

  -- de strategie als DATA (nooit code)
  specification       jsonb,                    -- StrategySpec (whitelist-gevalideerd)
  hypothesis          text,
  score               numeric,                  -- research-evaluatorscore 0-100
  research_metrics    jsonb,                    -- snapshot: is/oos/wf/robustness/flags/regimes

  -- lifecycle (zie lib/evolution/lifecycle.ts; PAPER_ACTIVE is de ENIGE
  -- handelbare status; een LIVE-status bestaat hier niet)
  status              text not null
                       check (status in (
                         'HYPOTHESIS','TESTING','REJECTED','INSUFFICIENT_DATA',
                         'RESEARCH_CANDIDATE','VALIDATION_PENDING','PAPER_CANDIDATE',
                         'PAPER_ACTIVE','PAPER_VALIDATING','PAPER_APPROVED',
                         'ROLLED_BACK','DEPRECATED','LEGACY'
                       )),
  canary              boolean not null default false,
  is_legacy           boolean not null default false,

  -- auditvelden
  activated_at         timestamptz,
  deactivated_at       timestamptz,
  activation_reason    text,
  rollback_reason      text,
  cooldown_until       timestamptz,              -- re-activatieverbod na rollback

  unique (strategy_id, version)
);
create index if not exists idx_registry_status      on strategy_registry (status);
create index if not exists idx_registry_family      on strategy_registry (family);
create index if not exists idx_registry_parent      on strategy_registry (parent_strategy_id);

-- ── 2. strategy_activations (audit trail — Deel 39) ─────────────────────
create table if not exists strategy_activations (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  registry_id   bigint not null,
  action        text not null check (action in (
                  'register','validate','validate_pass','validate_fail',
                  'activate','rollback','deactivate','cooldown',
                  'duplicate_reject','conflict_skip','fail_closed_no_entry')),
  from_status   text,
  to_status     text,
  reason        text not null,
  performed_by  text not null,                    -- evolution-engine | elara | cron | manual
  metrics_at    jsonb
);
create index if not exists idx_activations_registry on strategy_activations (registry_id, created_at desc);
create index if not exists idx_activations_recent   on strategy_activations (created_at desc);

-- ── 3. strategy_paper_metrics (monitoring per versie — Deel 11/12) ───────
create table if not exists strategy_paper_metrics (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  registry_id   bigint not null,
  strategy_key  text not null,                    -- bijv. evo/rsi-dip-volfilter@2.0.0
  state         text not null check (state in ('INSUFFICIENT_DATA','OK','WARN','ROLLBACK')),
  drift         text,                             -- leesbare backtest-vs-paper vergelijking
  metrics       jsonb,                            -- volledige PaperMetrics-snapshot
  triggers      jsonb,
  warnings      jsonb
);
create index if not exists idx_paper_metrics_registry on strategy_paper_metrics (registry_id, created_at desc);
