-- ══════════════════════════════════════════════════════════════════════════
-- FASE 4 — PAPER VALIDATION ENGINE
-- supabase-phase4-setup.sql — idempotent, additief. 1× draaien in de
-- Supabase SQL Editor (net als phase 1-3).
--
-- Wijzigingen:
--   1. strategy_registry.status-constraint UITGEBREID met de Fase 4-
--      lifecycle-statussen (PAPER_PENDING, WAITING_FOR_CANARY_SLOT,
--      VALIDATION_EARLY, VALIDATION_PROGRESS, VALIDATION_READY, FAILED).
--      Nog steeds GEEN enkele LIVE-status — fysiek onmogelijk.
--   2. Nieuwe tabel paper_validation_runs — gebonden, idempotente
--      validatie-runs met unieke execution_id (1 run per strategie per
--      Amsterdamse dag; dubbele runs zijn DB-niveau onmogelijk).
--
-- Bestaande historische data blijft onaangetast (additief).
-- ══════════════════════════════════════════════════════════════════════════

-- ── 1. status-constraint vervangen (uitgebreide lijst, zelfde naam) ─────
-- oude constraint verwijderen (naam door Postgres zelf gegeven bij phase 3)
alter table strategy_registry
  drop constraint if exists strategy_registry_status_check;

alter table strategy_registry
  add constraint strategy_registry_status_check
  check (status in (
    -- Fase 3
    'HYPOTHESIS','TESTING','REJECTED','INSUFFICIENT_DATA',
    'RESEARCH_CANDIDATE','VALIDATION_PENDING','PAPER_CANDIDATE',
    'PAPER_ACTIVE','PAPER_VALIDATING','PAPER_APPROVED',
    'ROLLED_BACK','DEPRECATED','LEGACY',
    -- Fase 4
    'PAPER_PENDING','WAITING_FOR_CANARY_SLOT',
    'VALIDATION_EARLY','VALIDATION_PROGRESS','VALIDATION_READY','FAILED'
  ));

-- ── 2. paper_validation_runs ────────────────────────────────────────────
create table if not exists paper_validation_runs (
  id             bigint generated by default as identity primary key,
  created_at     timestamptz not null default now(),
  execution_id   text not null unique,           -- bijv. val-12-2026-09-10 (1× per dag per strategie)
  registry_id    bigint not null,
  strategy_key   text,
  verdict        text not null check (verdict in (
                   'RUNNING','INSUFFICIENT_DATA','VALIDATION_EARLY','VALIDATION_PROGRESS',
                   'VALIDATION_READY','PAPER_APPROVED','FAILED','ERROR')),
  report         jsonb,                          -- volledig validatierapport (metrics/drift/gate)
  duration_ms    int
);

create index if not exists idx_val_runs_registry on paper_validation_runs (registry_id, created_at desc);
create index if not exists idx_val_runs_recent   on paper_validation_runs (created_at desc);
